[env:esp32s3]
platform = espressif32
framework = arduino
board = esp32-s3-devkitm-1

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

monitor_speed = 115200
upload_port = /dev/cu.usbserial-1420
monitor_port = /dev/cu.usbserial-1420

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE
    -Isrc

lib_deps =
    moononournation/GFX Library for Arduino@1.4.9
    kikuchan98/pngle@^1.1.0
    tamctec/TAMC_GT911@^1.0.2
    lvgl/lvgl@^8.4.0
    bblanchon/ArduinoJson@^7.0.0
    Wire
